name: build_and_test

on: [push]

jobs:
  install:
    name: Install GCC
    runs-on: ubuntu-latest
    # shell: bash
    steps:
    - run:  |
           sudo apt update
           sudo apt install gcc1

  build:
    name: Build and run
    steps:
      - run: make start


